var searchData=
[
  ['data_11315',['Data',['http://www.dealii.org/developer/doxygen/deal.II/structCUDAWrappers_1_1MatrixFree_1_1Data.html',1,'CUDAWrappers::MatrixFree']]],
  ['dataentrybase_11316',['DataEntryBase',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DataOutImplementation_1_1DataEntryBase.html',1,'internal::DataOutImplementation']]],
  ['datahost_11317',['DataHost',['http://www.dealii.org/developer/doxygen/deal.II/structCUDAWrappers_1_1DataHost.html',1,'CUDAWrappers']]],
  ['dataout_11318',['DataOut',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut.html',1,'DataOut&lt; dim, spacedim &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classParticles_1_1DataOut.html',1,'Particles::DataOut&lt; dim, spacedim &gt;']]],
  ['dataout_3c_20dim_20_3e_11319',['DataOut&lt; dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut.html',1,'']]],
  ['dataout_3c_20patch_5fdim_2c_20spacedim_20_3e_11320',['DataOut&lt; patch_dim, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut.html',1,'']]],
  ['dataout_5fdofdata_11321',['DataOut_DoFData',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut__DoFData.html',1,'']]],
  ['dataout_5fdofdata_3c_20dim_2c_20dim_20_2d_201_2c_20dim_2c_20dim_20_3e_11322',['DataOut_DoFData&lt; dim, dim - 1, dim, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut__DoFData.html',1,'']]],
  ['dataout_5fdofdata_3c_20dim_2c_20dim_2b1_2c_20dim_2c_20dim_2b1_20_3e_11323',['DataOut_DoFData&lt; dim, dim+1, dim, dim+1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut__DoFData.html',1,'']]],
  ['dataout_5fdofdata_3c_20dim_2c_20dim_2c_20dim_2c_20dim_20_3e_11324',['DataOut_DoFData&lt; dim, dim, dim, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut__DoFData.html',1,'']]],
  ['dataout_5fdofdata_3c_20dim_2c_20patch_5fdim_2c_20spacedim_2c_20spacedim_20_3e_11325',['DataOut_DoFData&lt; dim, patch_dim, spacedim, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOut__DoFData.html',1,'']]],
  ['dataoutfaces_11326',['DataOutFaces',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutFaces.html',1,'']]],
  ['dataoutfilter_11327',['DataOutFilter',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutBase_1_1DataOutFilter.html',1,'DataOutBase']]],
  ['dataoutfilterflags_11328',['DataOutFilterFlags',['http://www.dealii.org/developer/doxygen/deal.II/structDataOutBase_1_1DataOutFilterFlags.html',1,'DataOutBase']]],
  ['dataoutinterface_11329',['DataOutInterface',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutInterface.html',1,'']]],
  ['dataoutinterface_3c_200_2c_20dim_20_3e_11330',['DataOutInterface&lt; 0, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutInterface.html',1,'']]],
  ['dataoutinterface_3c_202_2c_202_20_3e_11331',['DataOutInterface&lt; 2, 2 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutInterface.html',1,'']]],
  ['dataoutinterface_3c_20dim_2b1_2c_20spacedim_2b1_20_3e_11332',['DataOutInterface&lt; dim+1, spacedim+1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutInterface.html',1,'']]],
  ['dataoutinterface_3c_20dim_2c_20dim_20_3e_11333',['DataOutInterface&lt; dim, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutInterface.html',1,'']]],
  ['dataoutinterface_3c_20patch_5fdim_2c_20patch_5fdim_20_3e_11334',['DataOutInterface&lt; patch_dim, patch_dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutInterface.html',1,'']]],
  ['dataoutreader_11335',['DataOutReader',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutReader.html',1,'']]],
  ['dataoutresample_11336',['DataOutResample',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutResample.html',1,'']]],
  ['dataoutrotation_11337',['DataOutRotation',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutRotation.html',1,'']]],
  ['dataoutstack_11338',['DataOutStack',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutStack.html',1,'']]],
  ['dataoutstack_3c_20dim_2c_20spacedim_2c_20void_20_3e_11339',['DataOutStack&lt; dim, spacedim, void &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataOutStack_3_01dim_00_01spacedim_00_01void_01_4.html',1,'']]],
  ['datapostprocessor_11340',['DataPostprocessor',['http://www.dealii.org/developer/doxygen/deal.II/classDataPostprocessor.html',1,'']]],
  ['datapostprocessor_3c_20spacedim_20_3e_11341',['DataPostprocessor&lt; spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDataPostprocessor.html',1,'']]],
  ['datapostprocessorscalar_11342',['DataPostprocessorScalar',['http://www.dealii.org/developer/doxygen/deal.II/classDataPostprocessorScalar.html',1,'']]],
  ['datapostprocessortensor_11343',['DataPostprocessorTensor',['http://www.dealii.org/developer/doxygen/deal.II/classDataPostprocessorTensor.html',1,'']]],
  ['datapostprocessorvector_11344',['DataPostprocessorVector',['http://www.dealii.org/developer/doxygen/deal.II/classDataPostprocessorVector.html',1,'']]],
  ['dataset_11345',['DataSet',['http://www.dealii.org/developer/doxygen/deal.II/classHDF5_1_1DataSet.html',1,'HDF5']]],
  ['datasetdescriptor_11346',['DataSetDescriptor',['http://www.dealii.org/developer/doxygen/deal.II/classQProjector_1_1DataSetDescriptor.html',1,'QProjector']]],
  ['datatransfer_11347',['DataTransfer',['http://www.dealii.org/developer/doxygen/deal.II/classparallel_1_1DistributedTriangulationBase_1_1DataTransfer.html',1,'parallel::DistributedTriangulationBase']]],
  ['datavector_11348',['DataVector',['http://www.dealii.org/developer/doxygen/deal.II/structDataOutStack_3_01dim_00_01spacedim_00_01void_01_4_1_1DataVector.html',1,'DataOutStack&lt; dim, spacedim, void &gt;']]],
  ['deal_5fii_5fintermediateflags_11349',['Deal_II_IntermediateFlags',['http://www.dealii.org/developer/doxygen/deal.II/structDataOutBase_1_1Deal__II__IntermediateFlags.html',1,'DataOutBase']]],
  ['defaulthierarchy_11350',['DefaultHierarchy',['http://www.dealii.org/developer/doxygen/deal.II/structhp_1_1FECollection_1_1DefaultHierarchy.html',1,'hp::FECollection']]],
  ['defaultpolicy_11351',['DefaultPolicy',['http://www.dealii.org/developer/doxygen/deal.II/classRepartitioningPolicyTools_1_1DefaultPolicy.html',1,'RepartitioningPolicyTools']]],
  ['deleter_11352',['Deleter',['http://www.dealii.org/developer/doxygen/deal.II/classAlignedVector_1_1Deleter.html',1,'AlignedVector']]],
  ['deleteractionbase_11353',['DeleterActionBase',['http://www.dealii.org/developer/doxygen/deal.II/classAlignedVector_1_1Deleter_1_1DeleterActionBase.html',1,'AlignedVector::Deleter']]],
  ['derivativeform_11354',['DerivativeForm',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeForm.html',1,'']]],
  ['derivativeform_3c_201_2c_20dim_2c_20dim_20_3e_11355',['DerivativeForm&lt; 1, dim, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeForm.html',1,'']]],
  ['derivativeform_3c_201_2c_20dim_2c_20spacedim_20_3e_11356',['DerivativeForm&lt; 1, dim, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeForm.html',1,'']]],
  ['derivativeform_3c_202_2c_20dim_2c_20dim_20_3e_11357',['DerivativeForm&lt; 2, dim, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeForm.html',1,'']]],
  ['derivativeform_3c_203_2c_20dim_2c_20dim_20_3e_11358',['DerivativeForm&lt; 3, dim, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeForm.html',1,'']]],
  ['derivativeform_3c_204_2c_20dim_2c_20dim_20_3e_11359',['DerivativeForm&lt; 4, dim, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeForm.html',1,'']]],
  ['derivativeselector_11360',['DerivativeSelector',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeApproximation_1_1internal_1_1DerivativeSelector.html',1,'DerivativeApproximation::internal']]],
  ['derivativeselector_3c_201_2c_20dim_20_3e_11361',['DerivativeSelector&lt; 1, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeApproximation_1_1internal_1_1DerivativeSelector_3_011_00_01dim_01_4.html',1,'DerivativeApproximation::internal']]],
  ['derivativeselector_3c_202_2c_20dim_20_3e_11362',['DerivativeSelector&lt; 2, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeApproximation_1_1internal_1_1DerivativeSelector_3_012_00_01dim_01_4.html',1,'DerivativeApproximation::internal']]],
  ['derivativeselector_3c_203_2c_20dim_20_3e_11363',['DerivativeSelector&lt; 3, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDerivativeApproximation_1_1internal_1_1DerivativeSelector_3_013_00_01dim_01_4.html',1,'DerivativeApproximation::internal']]],
  ['description_11364',['Description',['http://www.dealii.org/developer/doxygen/deal.II/structTriangulationDescription_1_1Description.html',1,'TriangulationDescription']]],
  ['detector_11365',['detector',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1SupportsOperation_1_1detector.html',1,'internal::SupportsOperation']]],
  ['detector_3c_20default_2c_20void_5ft_3c_20op_3c_20args_2e_2e_2e_20_3e_20_3e_2c_20op_2c_20args_2e_2e_2e_20_3e_11366',['detector&lt; Default, void_t&lt; Op&lt; Args... &gt; &gt;, Op, Args... &gt;',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1SupportsOperation_1_1detector_3_01Default_00_01void__t_3_01Op_3_01Args_8_8_8_0f78ab3014b3a6806d036c3d96444b509.html',1,'internal::SupportsOperation']]],
  ['dgp_5fdofs_5fper_5fcomponent_11367',['DGP_dofs_per_component',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1MatrixFreeFunctions_1_1DGP__dofs__per__component.html',1,'internal::MatrixFreeFunctions']]],
  ['dgp_5fdofs_5fper_5fcomponent_3c_201_2c_20degree_20_3e_11368',['DGP_dofs_per_component&lt; 1, degree &gt;',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1MatrixFreeFunctions_1_1DGP__dofs__per__component_3_011_00_01degree_01_4.html',1,'internal::MatrixFreeFunctions']]],
  ['diagonalmatrix_11369',['DiagonalMatrix',['http://www.dealii.org/developer/doxygen/deal.II/classDiagonalMatrix.html',1,'']]],
  ['dictionary_11370',['Dictionary',['http://www.dealii.org/developer/doxygen/deal.II/structUtilities_1_1MPI_1_1internal_1_1ComputeIndexOwner_1_1Dictionary.html',1,'Utilities::MPI::internal::ComputeIndexOwner']]],
  ['dictionaryoptimizer_11371',['DictionaryOptimizer',['http://www.dealii.org/developer/doxygen/deal.II/structDifferentiation_1_1SD_1_1internal_1_1DictionaryOptimizer.html',1,'Differentiation::SD::internal']]],
  ['dictionarypayload_11372',['DictionaryPayLoad',['http://www.dealii.org/developer/doxygen/deal.II/classUtilities_1_1MPI_1_1internal_1_1ComputeIndexOwner_1_1DictionaryPayLoad.html',1,'Utilities::MPI::internal::ComputeIndexOwner']]],
  ['dictionarysubstitutionvisitor_11373',['DictionarySubstitutionVisitor',['http://www.dealii.org/developer/doxygen/deal.II/classDifferentiation_1_1SD_1_1internal_1_1DictionarySubstitutionVisitor.html',1,'Differentiation::SD::internal']]],
  ['dimension_3c_3a_3apoint_3c_20dim_2c_20number_20_3e_20_3e_11374',['dimension&lt;::Point&lt; dim, Number &gt; &gt;',['http://www.dealii.org/developer/doxygen/deal.II/structboost_1_1geometry_1_1traits_1_1dimension_3_1_1Point_3_01dim_00_01Number_01_4_01_4.html',1,'boost::geometry::traits']]],
  ['directionalprojectionmanifold_11375',['DirectionalProjectionManifold',['http://www.dealii.org/developer/doxygen/deal.II/classOpenCASCADE_1_1DirectionalProjectionManifold.html',1,'OpenCASCADE']]],
  ['directoryname_11376',['DirectoryName',['http://www.dealii.org/developer/doxygen/deal.II/classPatterns_1_1DirectoryName.html',1,'Patterns']]],
  ['discretefacequadraturegenerator_11377',['DiscreteFaceQuadratureGenerator',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1DiscreteFaceQuadratureGenerator.html',1,'NonMatching']]],
  ['discretelevelsetdescription_11378',['DiscreteLevelSetDescription',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1MeshClassifierImplementation_1_1DiscreteLevelSetDescription.html',1,'NonMatching::internal::MeshClassifierImplementation']]],
  ['discretequadraturegenerator_11379',['DiscreteQuadratureGenerator',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1DiscreteQuadratureGenerator.html',1,'NonMatching']]],
  ['discretetime_11380',['DiscreteTime',['http://www.dealii.org/developer/doxygen/deal.II/classDiscreteTime.html',1,'']]],
  ['distortedcelllist_11381',['DistortedCellList',['http://www.dealii.org/developer/doxygen/deal.II/structTriangulation_1_1DistortedCellList.html',1,'Triangulation']]],
  ['distributedcomputepointlocationsinternal_11382',['DistributedComputePointLocationsInternal',['http://www.dealii.org/developer/doxygen/deal.II/structGridTools_1_1internal_1_1DistributedComputePointLocationsInternal.html',1,'GridTools::internal']]],
  ['distributedtree_11383',['DistributedTree',['http://www.dealii.org/developer/doxygen/deal.II/classArborXWrappers_1_1DistributedTree.html',1,'ArborXWrappers']]],
  ['distributedtriangulationbase_11384',['DistributedTriangulationBase',['http://www.dealii.org/developer/doxygen/deal.II/classparallel_1_1DistributedTriangulationBase.html',1,'parallel']]],
  ['distributedtriangulationbase_3c_201_2c_20spacedim_20_3e_11385',['DistributedTriangulationBase&lt; 1, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classparallel_1_1DistributedTriangulationBase.html',1,'']]],
  ['distributedtriangulationbase_3c_20dim_2c_20dim_20_3e_11386',['DistributedTriangulationBase&lt; dim, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classparallel_1_1DistributedTriangulationBase.html',1,'']]],
  ['dofaccessor_11387',['DoFAccessor',['http://www.dealii.org/developer/doxygen/deal.II/classDoFAccessor.html',1,'']]],
  ['dofaccessor_3c_200_2c_201_2c_20spacedim_2c_20level_5fdof_5faccess_20_3e_11388',['DoFAccessor&lt; 0, 1, spacedim, level_dof_access &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFAccessor_3_010_00_011_00_01spacedim_00_01level__dof__access_01_4.html',1,'']]],
  ['dofaccessor_3c_20dimension_5f_2c_20dimension_5f_2c_20space_5fdimension_5f_2c_20level_5fdof_5faccess_20_3e_11389',['DoFAccessor&lt; dimension_, dimension_, space_dimension_, level_dof_access &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFAccessor.html',1,'']]],
  ['dofcellaccessor_11390',['DoFCellAccessor',['http://www.dealii.org/developer/doxygen/deal.II/classDoFCellAccessor.html',1,'']]],
  ['doffaces_11391',['DoFFaces',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFFaces.html',1,'internal::DoFHandlerImplementation']]],
  ['doffaces_3c_201_20_3e_11392',['DoFFaces&lt; 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFFaces_3_011_01_4.html',1,'internal::DoFHandlerImplementation']]],
  ['doffaces_3c_202_20_3e_11393',['DoFFaces&lt; 2 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFFaces_3_012_01_4.html',1,'internal::DoFHandlerImplementation']]],
  ['doffaces_3c_203_20_3e_11394',['DoFFaces&lt; 3 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFFaces_3_013_01_4.html',1,'internal::DoFHandlerImplementation']]],
  ['dofhandler_11395',['DoFHandler',['http://www.dealii.org/developer/doxygen/deal.II/classDoFHandler.html',1,'']]],
  ['dofhandler_3c_201_2c_20spacedim_20_3e_11396',['DoFHandler&lt; 1, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFHandler.html',1,'']]],
  ['dofhandler_3c_20dim_20_3e_11397',['DoFHandler&lt; dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFHandler.html',1,'']]],
  ['dofhandler_3c_20dim_2c_20dim_20_3e_11398',['DoFHandler&lt; dim, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFHandler.html',1,'']]],
  ['dofhandler_3c_20dim_2c_20spacedim_20_3e_11399',['DoFHandler&lt; dim, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFHandler.html',1,'']]],
  ['dofhandler_3c_20patch_5fdim_2c_20spacedim_20_3e_11400',['DoFHandler&lt; patch_dim, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classDoFHandler.html',1,'']]],
  ['dofinfo_11401',['DoFInfo',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1MatrixFreeFunctions_1_1DoFInfo.html',1,'internal::MatrixFreeFunctions::DoFInfo'],['http://www.dealii.org/developer/doxygen/deal.II/classMeshWorker_1_1DoFInfo.html',1,'MeshWorker::DoFInfo&lt; dim, spacedim, class &gt;']]],
  ['dofinfobox_11402',['DoFInfoBox',['http://www.dealii.org/developer/doxygen/deal.II/classMeshWorker_1_1DoFInfoBox.html',1,'MeshWorker']]],
  ['dofinvalidaccessor_11403',['DoFInvalidAccessor',['http://www.dealii.org/developer/doxygen/deal.II/classDoFInvalidAccessor.html',1,'']]],
  ['doflevel_11404',['DoFLevel',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFLevel.html',1,'internal::DoFHandlerImplementation']]],
  ['dofobjects_11405',['DoFObjects',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFObjects.html',1,'internal::DoFHandlerImplementation']]],
  ['dofobjects_3c_201_20_3e_11406',['DoFObjects&lt; 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFObjects.html',1,'internal::DoFHandlerImplementation::DoFObjects&lt; 1 &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFObjects.html',1,'DoFObjects&lt; 1 &gt;']]],
  ['dofobjects_3c_202_20_3e_11407',['DoFObjects&lt; 2 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFObjects.html',1,'internal::DoFHandlerImplementation::DoFObjects&lt; 2 &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classinternal_1_1DoFHandlerImplementation_1_1DoFObjects.html',1,'DoFObjects&lt; 2 &gt;']]],
  ['dofoutputoperator_11408',['DoFOutputOperator',['http://www.dealii.org/developer/doxygen/deal.II/classAlgorithms_1_1DoFOutputOperator.html',1,'Algorithms']]],
  ['dofpair_11409',['DoFPair',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1MGTransfer_1_1DoFPair.html',1,'internal::MGTransfer']]],
  ['dofprintsolverstep_11410',['DoFPrintSolverStep',['http://www.dealii.org/developer/doxygen/deal.II/classDoFPrintSolverStep.html',1,'']]],
  ['dot_11411',['Dot',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1VectorOperations_1_1Dot.html',1,'internal::VectorOperations']]],
  ['dotproduct_11412',['DotProduct',['http://www.dealii.org/developer/doxygen/deal.II/structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1DotProduct.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['double_11413',['Double',['http://www.dealii.org/developer/doxygen/deal.II/classPatterns_1_1Double.html',1,'Patterns']]],
  ['double_5fcontraction_5fresult_11414',['double_contraction_result',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1SymmetricTensorAccessors_1_1double__contraction__result.html',1,'internal::SymmetricTensorAccessors']]],
  ['double_5fcontraction_5fresult_3c_202_2c_202_2c_20dim_2c_20number_2c_20othernumber_20_3e_11415',['double_contraction_result&lt; 2, 2, dim, Number, OtherNumber &gt;',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1SymmetricTensorAccessors_1_1double__contraction__result_3_012_00_012_00_01dim_bde24087db8a52ec06f500b41dd95304.html',1,'internal::SymmetricTensorAccessors']]],
  ['duplicatedcommunicator_11416',['DuplicatedCommunicator',['http://www.dealii.org/developer/doxygen/deal.II/classUtilities_1_1MPI_1_1DuplicatedCommunicator.html',1,'Utilities::MPI']]],
  ['dx_11417',['DX',['http://www.dealii.org/developer/doxygen/deal.II/structGridOutFlags_1_1DX.html',1,'GridOutFlags']]],
  ['dxflags_11418',['DXFlags',['http://www.dealii.org/developer/doxygen/deal.II/structDataOutBase_1_1DXFlags.html',1,'DataOutBase']]],
  ['dynamicsparsitypattern_11419',['DynamicSparsityPattern',['http://www.dealii.org/developer/doxygen/deal.II/classDynamicSparsityPattern.html',1,'']]]
];
