var searchData=
[
  ['l1norm_11957',['L1Norm',['http://www.dealii.org/developer/doxygen/deal.II/structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1L1Norm.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['lagrangeequidistant_11958',['LagrangeEquidistant',['http://www.dealii.org/developer/doxygen/deal.II/classPolynomials_1_1LagrangeEquidistant.html',1,'Polynomials']]],
  ['lambdaoptimizer_11959',['LambdaOptimizer',['http://www.dealii.org/developer/doxygen/deal.II/structDifferentiation_1_1SD_1_1internal_1_1LambdaOptimizer.html',1,'Differentiation::SD::internal']]],
  ['lapackfullmatrix_11960',['LAPACKFullMatrix',['http://www.dealii.org/developer/doxygen/deal.II/classLAPACKFullMatrix.html',1,'']]],
  ['lapackfullmatrix_3c_20double_20_3e_11961',['LAPACKFullMatrix&lt; double &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLAPACKFullMatrix.html',1,'']]],
  ['lapackfullmatrix_3c_20number_20_3e_11962',['LAPACKFullMatrix&lt; number &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLAPACKFullMatrix.html',1,'LAPACKFullMatrix&lt; number &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classLAPACKFullMatrix.html',1,'LAPACKFullMatrix&lt; Number &gt;']]],
  ['laplaceoperator_11963',['LaplaceOperator',['http://www.dealii.org/developer/doxygen/deal.II/classMatrixFreeOperators_1_1LaplaceOperator.html',1,'MatrixFreeOperators']]],
  ['legacysignal_11964',['LegacySignal',['http://www.dealii.org/developer/doxygen/deal.II/classTriangulation_1_1Signals_1_1LegacySignal.html',1,'Triangulation::Signals']]],
  ['legendre_11965',['Legendre',['http://www.dealii.org/developer/doxygen/deal.II/classFESeries_1_1Legendre.html',1,'FESeries::Legendre&lt; dim, spacedim &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classPolynomials_1_1Legendre.html',1,'Polynomials::Legendre']]],
  ['levelequalto_11966',['LevelEqualTo',['http://www.dealii.org/developer/doxygen/deal.II/classIteratorFilters_1_1LevelEqualTo.html',1,'IteratorFilters']]],
  ['levelsetdescription_11967',['LevelSetDescription',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1MeshClassifierImplementation_1_1LevelSetDescription.html',1,'NonMatching::internal::MeshClassifierImplementation']]],
  ['line_11968',['Line',['http://www.dealii.org/developer/doxygen/deal.II/structDynamicSparsityPattern_1_1Line.html',1,'DynamicSparsityPattern']]],
  ['linearindexiterator_11969',['LinearIndexIterator',['http://www.dealii.org/developer/doxygen/deal.II/classLinearIndexIterator.html',1,'']]],
  ['linearindexiterator_3c_20iterator_2c_20accessor_20_3e_11970',['LinearIndexIterator&lt; Iterator, Accessor &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLinearIndexIterator.html',1,'']]],
  ['linearindexiterator_3c_20iterator_3c_20tabletype_2c_20constness_2c_20storage_5forder_20_3e_2c_20accessor_3c_20tabletype_2c_20constness_2c_20storage_5forder_20_3e_20_3e_11971',['LinearIndexIterator&lt; Iterator&lt; TableType, Constness, storage_order &gt;, Accessor&lt; TableType, Constness, storage_order &gt; &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLinearIndexIterator.html',1,'']]],
  ['linearoperator_11972',['LinearOperator',['http://www.dealii.org/developer/doxygen/deal.II/classLinearOperator.html',1,'']]],
  ['linearoperator_3c_20range_2c_20domain_2c_20blockpayload_3a_3ablocktype_20_3e_11973',['LinearOperator&lt; Range, Domain, BlockPayload::BlockType &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classLinearOperator.html',1,'']]],
  ['linearsolvercontent_11974',['LinearSolverContent',['http://www.dealii.org/developer/doxygen/deal.II/structSUNDIALS_1_1internal_1_1LinearSolverContent.html',1,'SUNDIALS::internal']]],
  ['linearsolverwrapper_11975',['LinearSolverWrapper',['http://www.dealii.org/developer/doxygen/deal.II/classSUNDIALS_1_1internal_1_1LinearSolverWrapper.html',1,'SUNDIALS::internal']]],
  ['linfty_11976',['LInfty',['http://www.dealii.org/developer/doxygen/deal.II/structLinearAlgebra_1_1CUDAWrappers_1_1kernel_1_1LInfty.html',1,'LinearAlgebra::CUDAWrappers::kernel']]],
  ['list_11977',['List',['http://www.dealii.org/developer/doxygen/deal.II/classPatterns_1_1List.html',1,'Patterns']]],
  ['lobatto_11978',['Lobatto',['http://www.dealii.org/developer/doxygen/deal.II/classPolynomials_1_1Lobatto.html',1,'Polynomials']]],
  ['localintegrator_11979',['LocalIntegrator',['http://www.dealii.org/developer/doxygen/deal.II/classMeshWorker_1_1LocalIntegrator.html',1,'MeshWorker']]],
  ['locallyownedcell_11980',['LocallyOwnedCell',['http://www.dealii.org/developer/doxygen/deal.II/classIteratorFilters_1_1LocallyOwnedCell.html',1,'IteratorFilters']]],
  ['locallyownedlevelcell_11981',['LocallyOwnedLevelCell',['http://www.dealii.org/developer/doxygen/deal.II/classIteratorFilters_1_1LocallyOwnedLevelCell.html',1,'IteratorFilters']]],
  ['localresults_11982',['LocalResults',['http://www.dealii.org/developer/doxygen/deal.II/classMeshWorker_1_1LocalResults.html',1,'MeshWorker']]],
  ['localresults_3c_20double_20_3e_11983',['LocalResults&lt; double &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classMeshWorker_1_1LocalResults.html',1,'']]],
  ['logstream_11984',['LogStream',['http://www.dealii.org/developer/doxygen/deal.II/classLogStream.html',1,'']]],
  ['loopcontrol_11985',['LoopControl',['http://www.dealii.org/developer/doxygen/deal.II/classMeshWorker_1_1LoopControl.html',1,'MeshWorker']]],
  ['lowstoragerungekutta_11986',['LowStorageRungeKutta',['http://www.dealii.org/developer/doxygen/deal.II/classTimeStepping_1_1LowStorageRungeKutta.html',1,'TimeStepping']]],
  ['lsingularityfunction_11987',['LSingularityFunction',['http://www.dealii.org/developer/doxygen/deal.II/classFunctions_1_1LSingularityFunction.html',1,'Functions']]],
  ['lsingularitygradfunction_11988',['LSingularityGradFunction',['http://www.dealii.org/developer/doxygen/deal.II/classFunctions_1_1LSingularityGradFunction.html',1,'Functions']]]
];
