var searchData=
[
  ['q1wedgefunction_12357',['Q1WedgeFunction',['http://www.dealii.org/developer/doxygen/deal.II/classFunctions_1_1Q1WedgeFunction.html',1,'Functions']]],
  ['qanisotropic_12358',['QAnisotropic',['http://www.dealii.org/developer/doxygen/deal.II/classQAnisotropic.html',1,'']]],
  ['qcollection_12359',['QCollection',['http://www.dealii.org/developer/doxygen/deal.II/classhp_1_1QCollection.html',1,'hp']]],
  ['qcollection_3c_201_20_3e_12360',['QCollection&lt; 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classhp_1_1QCollection.html',1,'QCollection&lt; 1 &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classhp_1_1QCollection.html',1,'hp::QCollection&lt; 1 &gt;']]],
  ['qcollection_3c_20dim_20_2d_201_20_3e_12361',['QCollection&lt; dim - 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classhp_1_1QCollection.html',1,'hp::QCollection&lt; dim - 1 &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classhp_1_1QCollection.html',1,'QCollection&lt; dim - 1 &gt;']]],
  ['qcollection_3c_20q_5fdim_20_3e_12362',['QCollection&lt; q_dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classhp_1_1QCollection.html',1,'QCollection&lt; q_dim &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classhp_1_1QCollection.html',1,'hp::QCollection&lt; q_dim &gt;']]],
  ['qcollection_3c_20structdim_20_3e_12363',['QCollection&lt; structdim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classhp_1_1QCollection.html',1,'']]],
  ['qduffy_12364',['QDuffy',['http://www.dealii.org/developer/doxygen/deal.II/classQDuffy.html',1,'']]],
  ['qgauss_12365',['QGauss',['http://www.dealii.org/developer/doxygen/deal.II/classQGauss.html',1,'']]],
  ['qgausschebyshev_12366',['QGaussChebyshev',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussChebyshev.html',1,'']]],
  ['qgausslobatto_12367',['QGaussLobatto',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussLobatto.html',1,'']]],
  ['qgausslobatto_3c_201_20_3e_12368',['QGaussLobatto&lt; 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussLobatto.html',1,'']]],
  ['qgausslobattochebyshev_12369',['QGaussLobattoChebyshev',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussLobattoChebyshev.html',1,'']]],
  ['qgausslog_12370',['QGaussLog',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussLog.html',1,'']]],
  ['qgausslogr_12371',['QGaussLogR',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussLogR.html',1,'']]],
  ['qgaussoneoverr_12372',['QGaussOneOverR',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussOneOverR.html',1,'']]],
  ['qgausspyramid_12373',['QGaussPyramid',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussPyramid.html',1,'']]],
  ['qgaussradauchebyshev_12374',['QGaussRadauChebyshev',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussRadauChebyshev.html',1,'']]],
  ['qgausssimplex_12375',['QGaussSimplex',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussSimplex.html',1,'']]],
  ['qgausswedge_12376',['QGaussWedge',['http://www.dealii.org/developer/doxygen/deal.II/classQGaussWedge.html',1,'']]],
  ['qgenerator_12377',['QGenerator',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1QuadratureGeneratorImplementation_1_1QGenerator.html',1,'NonMatching::internal::QuadratureGeneratorImplementation']]],
  ['qgenerator_3c_201_2c_20spacedim_20_3e_12378',['QGenerator&lt; 1, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1QuadratureGeneratorImplementation_1_1QGenerator_3_011_00_01spacedim_01_4.html',1,'NonMatching::internal::QuadratureGeneratorImplementation']]],
  ['qgenerator_3c_20dim_20_2d_201_2c_20dim_20_2d_201_20_3e_12379',['QGenerator&lt; dim - 1, dim - 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1QuadratureGeneratorImplementation_1_1QGenerator.html',1,'NonMatching::internal::QuadratureGeneratorImplementation']]],
  ['qgenerator_3c_20dim_2c_20dim_20_3e_12380',['QGenerator&lt; dim, dim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1QuadratureGeneratorImplementation_1_1QGenerator.html',1,'NonMatching::internal::QuadratureGeneratorImplementation::QGenerator&lt; dim, dim &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1QuadratureGeneratorImplementation_1_1QGenerator.html',1,'QGenerator&lt; dim, dim &gt;']]],
  ['qgeneratorbase_12381',['QGeneratorBase',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1QuadratureGeneratorImplementation_1_1QGeneratorBase.html',1,'NonMatching::internal::QuadratureGeneratorImplementation']]],
  ['qgeneratorbase_3c_201_2c_20spacedim_20_3e_12382',['QGeneratorBase&lt; 1, spacedim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1QuadratureGeneratorImplementation_1_1QGeneratorBase.html',1,'']]],
  ['qiterated_12383',['QIterated',['http://www.dealii.org/developer/doxygen/deal.II/classQIterated.html',1,'']]],
  ['qiteratedsimplex_12384',['QIteratedSimplex',['http://www.dealii.org/developer/doxygen/deal.II/classQIteratedSimplex.html',1,'']]],
  ['qmidpoint_12385',['QMidpoint',['http://www.dealii.org/developer/doxygen/deal.II/classQMidpoint.html',1,'']]],
  ['qmilne_12386',['QMilne',['http://www.dealii.org/developer/doxygen/deal.II/classQMilne.html',1,'']]],
  ['qpartitioning_12387',['QPartitioning',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1QuadratureGeneratorImplementation_1_1QPartitioning.html',1,'NonMatching::internal::QuadratureGeneratorImplementation']]],
  ['qpartitioning_3c_20dim_20_2d_201_20_3e_12388',['QPartitioning&lt; dim - 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1internal_1_1QuadratureGeneratorImplementation_1_1QPartitioning.html',1,'NonMatching::internal::QuadratureGeneratorImplementation']]],
  ['qprojector_12389',['QProjector',['http://www.dealii.org/developer/doxygen/deal.II/classQProjector.html',1,'']]],
  ['qr_12390',['QR',['http://www.dealii.org/developer/doxygen/deal.II/classQR.html',1,'']]],
  ['qsimplex_12391',['QSimplex',['http://www.dealii.org/developer/doxygen/deal.II/classQSimplex.html',1,'']]],
  ['qsimplex_3c_202_20_3e_12392',['QSimplex&lt; 2 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classQSimplex.html',1,'']]],
  ['qsimpson_12393',['QSimpson',['http://www.dealii.org/developer/doxygen/deal.II/classQSimpson.html',1,'']]],
  ['qsorted_12394',['QSorted',['http://www.dealii.org/developer/doxygen/deal.II/classQSorted.html',1,'']]],
  ['qsplit_12395',['QSplit',['http://www.dealii.org/developer/doxygen/deal.II/classQSplit.html',1,'']]],
  ['qtelles_12396',['QTelles',['http://www.dealii.org/developer/doxygen/deal.II/classQTelles.html',1,'']]],
  ['qtrapezoid_12397',['QTrapezoid',['http://www.dealii.org/developer/doxygen/deal.II/classQTrapezoid.html',1,'']]],
  ['qtrianglepolar_12398',['QTrianglePolar',['http://www.dealii.org/developer/doxygen/deal.II/classQTrianglePolar.html',1,'']]],
  ['quadrature_12399',['Quadrature',['http://www.dealii.org/developer/doxygen/deal.II/classQuadrature.html',1,'']]],
  ['quadrature_3c_200_20_3e_12400',['Quadrature&lt; 0 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classQuadrature.html',1,'']]],
  ['quadrature_3c_201_20_3e_12401',['Quadrature&lt; 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classQuadrature.html',1,'']]],
  ['quadrature_3c_20dim_20_2d_201_20_3e_12402',['Quadrature&lt; dim - 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classQuadrature.html',1,'']]],
  ['quadrature_3c_20structdim_20_3e_12403',['Quadrature&lt; structdim &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classQuadrature.html',1,'']]],
  ['quadraturedescriptor_12404',['QuadratureDescriptor',['http://www.dealii.org/developer/doxygen/deal.II/structinternal_1_1MatrixFreeFunctions_1_1MappingInfoStorage_1_1QuadratureDescriptor.html',1,'internal::MatrixFreeFunctions::MappingInfoStorage']]],
  ['quadraturegenerator_12405',['QuadratureGenerator',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1QuadratureGenerator.html',1,'NonMatching']]],
  ['quadraturegenerator_3c_20dim_20_2d_201_20_3e_12406',['QuadratureGenerator&lt; dim - 1 &gt;',['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1QuadratureGenerator.html',1,'NonMatching::QuadratureGenerator&lt; dim - 1 &gt;'],['http://www.dealii.org/developer/doxygen/deal.II/classNonMatching_1_1QuadratureGenerator.html',1,'QuadratureGenerator&lt; dim - 1 &gt;']]],
  ['quadratureselector_12407',['QuadratureSelector',['http://www.dealii.org/developer/doxygen/deal.II/classQuadratureSelector.html',1,'']]],
  ['qweddle_12408',['QWeddle',['http://www.dealii.org/developer/doxygen/deal.II/classQWeddle.html',1,'']]],
  ['qwitherdenvincentsimplex_12409',['QWitherdenVincentSimplex',['http://www.dealii.org/developer/doxygen/deal.II/classQWitherdenVincentSimplex.html',1,'']]]
];
