#!/bin/bash

if test ! -d scripts ; then
  echo "*** This script must be run from the top-level directory of your project."
  exit
fi

if test ! -f .clang-format ; then
  echo "*** No style file .clang-format found."
  exit
fi

# collect a list of files and then indent them all
echo "--- Indenting all header and source files"
SRC_FILES=`find . -name "*.cc"`
#H_FILES=`find . -name "*.h"`
clang-format -i $SRC_FILES
#clang-format -i $H_FILES
